# Model Description {#modeldes}

We used a Bayesian state-space model to estimate annual Adélie nest abundances for all 271 known Adélie breeding sites from 1970 -- 2020, with an extra decade to 2030 to illustrate forecasting power. We model the intrinsic rate of growth $r_{it}$, for the $i_{th}$ site in $t_{th}$ season as a function of site effects. We purposefully avoided additional covariates as to create a simplistic default model whose predictive ability could be compared to that of more biologically nuanced process models. 

## Observation errors {#obserror}

Counts were provided by the observer(s) as the nest or chick count $y$ along with an associated accuracy score (which we convert to measurement error) such that $y$ represented a draw from a distribution:

$$\big[\,y \mid lz, \sigma^{2}_{o} \,\big]\textrm{,}$$

centered on the "true", or latent, count $lz$ whose dispersion was controlled by $\sigma^{2}_{o}$, which represented the uncertainty in the count due to measurement imprecision. The accuracy scores were selected from a 5 point scale that penguin census counters traditionally use to represent count precision (Croxall and Kirkwood, 1979). Based on this scale, if 100 nests was the true count then the 95% confidence intervals for each accuracy category's distribution was defined as:

| Reported accuracy | Reported 95% confidence interval |
|-------------------|-------------------------|
| 1 | (95, 105) |
| 2 | (90, 110) |
| 3 | (75, 125) |
| 4 | (50, 150) |
| 5 | (40, 245) |

Table 1: Reported accuracy categories and their confidence intervals.

We used the log-normal distribution to model the observation process, as all counts must be positive. However, the confidence intervals (with the exception of category 5) were symmetric around the true count and did not correspond to the skewed credible intervals generated by the log-normal distribution. To compute the appropriate scale parameters for each accuracy category, we defined a function `min.RSS` that outputed the squared deviations between the upper and lower confidence interval (Table 1) and the 0.975 and 0.025 quantiles from the cumulative density function for a log-normal distribution whose median was 100. We then used the `optim` function to select the scale parameter $\sigma_{o}$ that minimized the sums of squares for each accuracy category. For example:

``` {r, eval = FALSE, echo = TRUE}
min.RSS <- function(par = 0.02, start = 95, end = 105) {
  (qlnorm(0.9775, log(100), par) - end)^2 + (qlnorm(0.0225, log(100), par) - start)^2
}
optim(par = 0.02, min.RSS, method = "Brent", lower = 1e-04, upper = 10)
```

Using the optimized scale parameters, we computed 95% confidence intervals from log-normal distributions whose median was 100, i.e. the location parameter $\mu$ = log(100). To do this, we converted each scale parameter into its geometric standard deviations $(s^{*}=e^{\sigma_{o}})$ and calculated the 95% confidence interval as $(lz(s^{*})^{-2}, lz(s^{*})^{2})$. The scale parameters used in the Adélie observation model, their geometric standard deviations, and the adjusted 95% confidence intervals for each accuracy category were:

| Reported accuracy | Reported 95% CI | Adjusted 95% CI | $\sigma_{o}$ |
|-------------------|-------------------------|------------------|----------------------------------|
| 1 | (95, 105) | (95, 105) | 0.025 | 
| 2 | (90, 110) | (91, 110) | 0.050 |
| 3 | (75, 125) | (79, 127) | 0.120 |
| 4 | (50, 150) | (64, 156) | 0.230 | 
| 5 | (40, 245) | (41, 245) | 0.510 | 

Table 2: Reported accuracy categories mapped to log-normal scale parameters used in the Adélie model.

<br>

## Abundance process models {#bioprocess}

### Nest abundance

We build our nest abundance model modeling logged abundance using the *student t* distribution. Adopting Gelman and Hill's (2007) bracket notation for assigning group membership (for example, $s[35]=2$ means that the $35^{th}$ unit in the data ($i = 35$) is from group 2), we start by modeling "true" (hereafter latent) nest abundance $z_{i,t}$ at the $i_{th}$ breeding site located on or adjacent to the Antarctic Peninsula $(s=1)$ or continent $(s=2)$ in the $t_{th}$ season as:

$$
\log(z_{i,t}) \sim \textrm{student}t \big(\mu_{i,t} = \log(z_{i,t-1}e^{r_{i}}), \sigma^2, \nu \big)\textrm{,} (\#eq:lnnests)
$$
where the mean of the student t distribution, $\mu_{i,t}$, is a deterministic model for discrete exponential growth, such that nest abundance $z_{i,t}$ is the product of nest abundance in the previous season $z_{i,t-1}$ at the site and the intrinsic rate of growth, $r_{i}$. We model the intrinsic growth rate as the sum of a grand mean $\gamma$ and site effects $\eta_{i}$:

$$
r_{i} = \gamma + \eta_{i},(\#eq:rintrinsic)
$$
where each modeled hierarchically as:

\begin{align} 
\eta_{i} & \sim \textrm{normal} \big(0, \sigma^{2}_{site}\big)(\#eq:intrinsicml)
\end{align}

In Equation \@ref(eq:lnnests) $\sigma^{2}$ represents process error, or the variation in logged (confusingly) latent nest abundance due to unmodeled biotic or abiotic processes not captured by the simple growth model embedded as the distribution's median; $\nu$ is the degrees of freedom of the student t distribution.


### Chick abundance {#chickabundance}

We modeled the latent chick abundance $zc_{i,t}$ at the $i_{th}$ breeding site in the $t_{th}$ season as:

\begin{align}
zc_{i,t} & \sim \textrm{binomial} \big(N_{i,t}, \alpha_{i,t} \big) (\#eq:lchicks1)\\
N_{i,t} & = 2 \times \textrm{round}(e^{lz_{i,t}}) (\#eq:lchicks2)\\
\alpha_{i, t} & \sim \textrm{beta} \big(a = 1.875, b =  1.125\big) \textrm{.} (\#eq:lchicks3)
\end{align}

Pygoscelid penguins typically produce one chick per nest (the maximum number of chicks per nest is two), although breeding success can fluctuate considerably between sites and seasons. We use the well-informed priors $\mu = 0.5, \sigma^{2} = 0.0625$ for $\alpha_{i,t}$, the proportion of chicks produced at the $i_{th}$ site in the $t_{th}$ season, to reflect observed variation in breeding success due to environmental and demographic stochasticity. Note that, when moment-matched, these priors result in $a$ and $b$ in Equation \@ref(eq:lchicks3).

### Initial season abundance {#initialseason}

We modeled the logged latent nest abundance at the $i_{th}$ site for the first season $(t=I_{i})$ nest abundance was recorded as:

$$
lz_{i,t=I_{i}} \sim \textrm{normal} \big(0, 1000000 \big).(\#eq:inests)
$$

### Regional groups {#rgroups}

We grouped sites into the following geographic regions prior to analysis:

1. Central-west and Northwest Antarctic Peninsula
2. Southwest Antarctic Peninsula and Palmer Land
3. Elephant Island, the South Orkney Islands, and the South Shetland Islands
4. Northeast Antarctic Peninsula
5. CCAMLR sub area 88.1 and 88.2
6. CCAMLR sub area 88.3
7. CCAMLR sub area 58.4.1
8. CCAMLR sub area 58.4.2

### Hindcasting explained

We hindcast logged latent nest abundances for the $i_{th}$ site from 1970 to the season prior to the initial season a count was recorded $(t = I_{i} - 1)$ as:

$$
lz_{i,t-1} \sim \textrm{student}t \big(lz_{i,t} - \gamma - \eta_{i}, d \big)\textrm{.}
$$

This method of hindcasting was possible because the exponential growth function can be inverted, making hindcasting nest abundances functionally no different than forecasting nest abundances into the future or in seasons of missing data within a site's time series. For sites whose first season of data was 1970, hindcasting was unnecessary.

## Observation process models {#obsprocess}

We modeled the logged observed nest counts $y_{{n}_{s}}$ and chick counts $y_{{c}_{s}}$ recorded at the $i_{th}$ breeding site in the $t_{th}$ season as:

\begin{align}
y_{{n}_{i,t}} & \sim \textrm{normal} \big(lz_{i,t} - \sigma^{2}_{{n}_{i,t}}/2, \sigma^{2}_{{n}_{i,t}}\big) (\#eq:onests)\\
y_{{c}_{i,t}} & \sim \textrm{normal} \big(lz_{i,t} - \sigma^{2}_{{n}_{i,t}}/2, \sigma^{2}_{{c}_{i,t}}\big)\textrm{,} (\#eq:ochicks)
\end{align}

where $\sigma^{2}_{n_{i, t}}$ and $\sigma^{2}_{c_{i, t}}$ are the observation errors in the recorded nest and chick count, respectively. These errors are computed from the accuracy ratings reported by the observer, the details of which are outlined in Section \@ref(obserror). Note that sites can have both nest and chick counts in the same season.

## Joint distribution {#joint}

We combine the relevant equations from Sections \@ref(bioprocess) and \@ref(obsprocess) along with the necessary prior distributions to specify the joint distribution for our model. Note that we have modified Equations \@ref(eq:lchicks1), \@ref(eq:lchicks3), \@ref(eq:onests), and \@ref(eq:ochicks) using the bracket notation described above to reflect the fact that most site-season combinations lack observed counts and latent site-level chick abundances and breeding productivites are only estimated for seasons when chick counts were recorded. We chose vague priors (on the log-scale), with the exception of $\alpha$.

\begin{align}
\big[\gamma, \boldsymbol{\alpha}, \boldsymbol{\eta}, \, & \boldsymbol{\sigma}, \sigma_{site}, \mathbf{lz}, \mathbf{zc} \mid \mathbf{y_{i}}, \mathbf{y_{n}}, \mathbf{y_{c}}, \boldsymbol{\sigma_{i}}, \boldsymbol{\sigma_{n}}, \boldsymbol{\sigma_{c}} \big]  \varpropto  \\
& \prod_{v=1}^{908} \textrm{normal} \big(y_{{n}_{v}} \mid lz_{i[v],t[v]} - \sigma^{2}_{{n}_{v}}/2, \sigma^{2}_{{n}_{v}}\big) \\
& \times \prod_{v=1}^{172} \textrm{normal} \big(y_{{c}_{v}} \mid \log(zc_{i[v],t[v]}) - \sigma^{2}_{{c}_{v}}/2, \sigma^{2}_{{c}_{v}}\big) \\
& \times \textrm{binomial} \big(zc_{i[v],t[v]} \mid N_{v} = \textrm{round}(\exp(lz_{i[v],t[v]}), \alpha_{v}\big) \, \textrm{beta} \big(\alpha_{v} \mid a = 1.875, b =  1.125\big)\\
& \times \prod_{i=1}^{271} \prod_{t=I_{i}\,+\,1}^{51} \textrm{logistic} \big(lz_{i,t} \mid lz_{i,t-1} +  \eta_{t}, d \big) \nonumber \\
& \times \prod_{t=1}^{I_{i}-1} \textrm{logistic} \big(lz_{i,t-1} \mid lz_{i,t} - \eta_{t}, d \big) \nonumber \\
& \times \textrm{logistic} \big(lz_{i, t=I_{i}} \mid 0, 1\textrm{E}6 \big)\, \textrm{normal} \big(\gamma \mid 0, 2 \big) \nonumber \\
&   \textrm{normal} \big( \eta_{i} \mid 0, \sigma^{2}_{site} \big) \nonumber \\
&\times \textrm{uniform} \big( \sigma_{s} \mid 0, 2 \big) \, \textrm{uniform} \big( \sigma_{site} \mid 0, 1 \big). \nonumber \\
\end{align}

## Additional assumptions {#addassumptions}

We made several modifications to the MAPPPD data prior to modeling:

1. We converted adults counts 1:1 to nest counts. We recognize that for any individual survey, this may not be the correct conversion factor. Adult counts may be reported when surveys are done very early in the season (prior to nesting) or when nests have not yet been established and the count of adults is too small. Alternatively, surveys may be conducted at a time when more than one adult is in attendance at some nests and the count of adults is too high. Because this conversion introduces an additional uncertainty in the conversion to nests, we decreased the accuracy of adult counts by 3 categories (with a maximum category of 5) relative to the reported uncertainty in the adult count itself. This approach is quite conservative, in that we likely overestimate the true uncertainty of those adult counts. 

2. We converted chick counts 1:1 to nest counts if the chick count was the only available count the first season data were recorded for a site. This was done to ensure that the time series for all sites originated with a nest count. The choice of conversion factor was made based on observed Pygoscelid breeding productivity discussed in Section \@ref(chickabundance). 

3. If there was more than one chick or nest count for a site in a season, we kept the maximum count and discarded the others. Nest and chick counts vary during the breeding season, as surveys can occur before or after peak breeding. While we would very much prefer to model breeding phenology each season as an additional component of the mode, the data are far to sparse for this to be possible. Instead, we use only the maximum count to best approximate peak breeding.

4. Although positive nest counts are estimated for each site from 1970-2030, the modeled time series we report on the MAPPPD website suppress site counts in seasons where Adélie penguins were not observed breeding (see #1 in Section \@ref(derivedq) for more details on how this was done). The occupancy data $(w_{i,t})$ necessary to censor time series in this fashion is a combination of MAPPPD counts flattened into presence/absence data and true presence/absence data also collected in MAPPPD. This data (like all MAPPPD data) is quite sparse, and there are many seasons where we do not know whether or not a site is used for breeding. This is problematic as there are cases where Adélie breeding sites were colonized after 1970, were extirpated prior to 2020, or were used intermittently during this time period. Also, it could be unclear when these breeding status changes happened, if they occurred during a multi-year gap between observations. Fortunately, Pygoscelid penguins in general are extremely site faithful, leading to stable breeding sites over long time scales, and the overwhelming majority of Adélie breeding sites in MAPPPD are likely to have been occupied continuously during during the 51 season interval for which we modeled nest abundance. In most cases, we assumed that the last observed breeding status persisted until a counterfactual observation was made. In a few cases, where a nesting site was known from past observations to only occasionally host breeding birds, the breeding status was assumed to be absent unless it was actually observed as being present. 

## Derived quantities {#derivedq}

We computed the following derived quantities from the parameters estimated in our model:

1. The logged latent seasonal nest abundance for the $i_{th}$ site in the $t_{th}$ year, while allowing for site extirpation and colonization events, as $lza_{i,t}=lz_{i,t}\cdot w_{i,t}$. Please see #3 in Section \@ref(addassumptions) for the details regarding $w_{i,t}$.

2. The aggregated logged latent seasonal nest abundances at the CCAMLR sub-area, regional, and continental scales, as the sum the posterior distributions of $lza_{i,t}$ for all constituent sites at each spatial scale. 

3. The predicted population growth rate multiplier $\lambda_{i,t}$ as $l_{p_{i}} = e^{r_{i}}$.

3. The actual population growth rate multiplier $\lambda_{i,t}$ as $l_{a_{i,t}} = e^{lz_{i,t+1}-lz_{i,t}}$.

4. The average population growth rate multipliers $\lambda_{i}$ for each site as the geometric mean of $l_{p_{i,t}}$ and $l_{a_{i,t}}$ for all transitions $t \to t+1$ breeding occurred in both seasons $(w_{i,t}=1 \land w_{i,t+1}=1)$ between 1970 and 2030. Please see #3 in Section \@ref(addassumptions) for the details regarding $w_{i,t}$. 

## Bibliography

1. Croxall, J. P. & Kirkwood, E. D. *The distribution of penguins on the Antarctic Peninsula and Islands of the Scotia Sea*. (British Antarctic Survey, Cambridge, United Kingdom, 1979).

2. Gelman, A. & Hill, J. *Data Analysis Using Regression and Multilevel/Hierarchical Models*. (Cambridge University Press, New York, New York, 2007).


