# Data Setup

## MAPPPDR to JAGS

The following R code generates the JAGS data list object needed for fitting the model. Please see Section \@ref(modeldes) for further details, especially with regards to the various commented assumptions.

```{r, eval = TRUE, echo = TRUE, message = FALSE}
min_season <- 1970
max_season <- 2020 # 2030
species <- "ADPE"

# assign the total number of seasons as n_seasons
(n_seasons <- (max_season - min_season) + 1)

SiteList <- mapppdr::penguin_obs %>%
  # keep all sites that have at least 1 count between min and max season
  dplyr::filter(count > 0 & species_id == species & season >= min_season & season <= max_season) %>%
  # create relative season index 
  mutate(season_relative = season - min_season + 1) %>%
  # determine first season a count is observed for each site
  group_by(site_id) %>%
  summarise(initial_season = min(season_relative)) %>%
  ungroup() %>%
  # join to get other site specific covariates for visualization purposes
  left_join(mapppdr::sites, by = "site_id") %>%
  # create site index for model and visualization
  mutate(site = as.numeric(as.factor(site_id))) %>%
  # great regional groupings
  mutate(region_id = case_when(
    region == "Central-west Antarctic Peninsula" ~ 1, 
    region == "Northwest Antarctic Peninsula" ~ 1,
    region == "Southwest Antarctic Peninsula" ~ 2, 
    region == "Palmer Land" ~ 2, 
    region == "Elephant Island" ~ 3, 
    region == "South Orkney Islands" ~ 3, 
    region == "South Shetland Islands" ~ 3, 
    region == "Northeast Antarctic Peninsula" ~ 4,     
    ccamlr_id == "88.1" ~ 5, 
    ccamlr_id == "88.2" ~ 5, 
    ccamlr_id == "88.3" ~ 6,
    ccamlr_id == "58.4.1" ~ 7, 
    ccamlr_id == "58.4.2" ~ 8)) %>%   
  mutate(ccamlr = case_when(
    ccamlr_id == "48.1" ~ 1, 
    ccamlr_id == "48.2" ~ 1,
    ccamlr_id == "88.1" ~ 2, 
    ccamlr_id == "88.2" ~ 2, 
    ccamlr_id == "88.3" ~ 2,
    ccamlr_id == "58.4.1" ~ 2, 
    ccamlr_id == "58.4.2" ~ 2)) %>%     
  dplyr::select(site_id, site_name, ccamlr, ccamlr_id, region = region_id, site, initial_season, latitude, longitude)

(n_sites <- nrow(SiteList))
(n_regions <- length(unique(SiteList$region)))
(n_ccamlr <- length(unique(SiteList$ccamlr)))

# create site x season template which is used throughout analysis
w_template <- SiteList %>%
  dplyr::select(site_id, site) %>%
  # expand each site by the number of seasons
  uncount(n_seasons) %>%
  # create relative season index for each site
  mutate(season_relative = rep(1:n_seasons, n_sites)) %>%
  # create season var from relative season index
  mutate(season = season_relative + min_season - 1) %>%
  arrange(season_relative, site)

w_df <- mapppdr::penguin_obs %>%
  # keep all presence/absence data and assign observation type as 1 (observed)
  dplyr::filter(species_id == species & season >= min_season & season <= max_season) %>%
  dplyr::select(site_id, season, presence) %>%
  mutate(known_w = 1) %>%
  # determine for each site x season if breeding is observed or assumed
  group_by(site_id, season) %>%
  summarise(w = base::max(presence), known_w = base::max(known_w)) %>%
  ungroup() %>%
  # join with w_template to fill in missing site x seasons with no presence/absence data
  right_join(w_template, by = c("site_id", "season")) %>%
  # assign observation type as 0 (imputed)
  mutate(known_w = replace(known_w, is.na(known_w), 0)) %>%
  arrange(site_id, season) %>%
  # impute missing presence/absence data using the following assumptions
  # ASSSUMPTION: fill in NA between (1,1) with 1
  # ASSSUMPTION: fill in NA between (0,1) with 0
  # ASSSUMPTION: fill in NA between (1,0) with 1
  # ASSSUMPTION: fill in NA between (.,1) and (1,.) with 1
  # ASSSUMPTION: fill in NA between (.,0) and (0,.) with 0
  dplyr::group_by(site_id) %>%
  tidyr::fill(w, .direction = "downup") %>%
  dplyr::ungroup() %>%
  # create second site_id var for plotting sites alphabetically in ggplot
  mutate(site_id_rev = factor(site_id, levels = rev(sort(unique(site_id))))) %>%
  dplyr::select(site_id, site_id_rev, season, site, season_relative, w, known_w)

# convert w to matrix to be used in model
w <- w_df %>%
  dplyr::select(site, season_relative, w) %>%
  # create matrix where rows are sites and columns are seasons
  pivot_wider(names_from = season_relative, values_from = w, names_sort = TRUE) %>%
  dplyr::select(-site) %>%
  as.matrix()

abundance <- mapppdr::penguin_obs %>%
  # keep all counts between min and max season
  dplyr::filter(count > 0 & species_id == species & season >= min_season & season <= max_season) %>%
  # join to get site index and initial season
  right_join(SiteList, by = "site_id") %>%
  # create relative season index 
  mutate(season_relative = season - min_season + 1) %>%
  # ASSUMPTION: increase accuracy category of all adult counts by + 3 with a max error of 5
  rowwise() %>%
  mutate(accuracy = replace(accuracy, type == "adults", base::min((accuracy[type == "adults"] + 3), 5))) %>%
  ungroup() %>%  
  mutate(type = replace(type, type == "adults", "nests")) %>%
  # ASSUMPTION: keep maximum nest and chick count reported each season for a site
  group_by(site_id, season, season_relative, type) %>%
  arrange(desc(count), accuracy) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  # ASSUMPTION: convert accuracy to the following errors/precisions
  mutate(sigma = case_when(
    accuracy == 1 ~ 0.02490061, 
    accuracy == 2 ~ 0.04955838,
    accuracy == 3 ~ 0.1201131, 
    accuracy == 4 ~ 0.2212992, 
    accuracy == 5 ~ 0.4472728)) %>%
  mutate(precision = case_when(
    accuracy == 1 ~ 1/0.02490061^2, 
    accuracy == 2 ~ 1/0.04955838^2,
    accuracy == 3 ~ 1/0.1201131^2, 
    accuracy == 4 ~ 1/0.2212992^2, 
    accuracy == 5 ~ 1/0.4472728^2)) %>%  
  dplyr::select(site_id, site, ccamlr, region, season, season_relative, initial_season, type, 
    count, presence, accuracy, sigma, precision) %>%
  arrange(site, season_relative, type, -count, accuracy, sigma, precision)  

abundance_initial <- abundance %>%
  # keep first observed count for each site's time series
  dplyr::filter(initial_season == season_relative) %>%
  # ASSUMPTION: if no nest count is available in the initial season and a chick count is then
  # assume chick count is 1:1 nest count
  group_by(site_id, season, site, season_relative) %>%
  arrange(desc(type)) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  dplyr::select(site_id, season, site, ccamlr, region, season_relative, count, sigma, precision)

abundance_nests <- abundance %>%
  # keep all nest counts after the initial season
  dplyr::filter(initial_season != season_relative & type == "nests") %>%
  dplyr::select(site_id, season, site, ccamlr, region, season_relative, count, sigma, precision)

abundance_chicks <- rbind(
  # keep all chick counts after the initial season
  abundance %>%
    dplyr::filter(initial_season != season_relative & type == "chicks") %>%
    dplyr::select(site_id, ccamlr, region, season, site, season_relative, count, sigma, precision),
  # append chick counts from initial season that were not converted to nest counts
  # meaning there was both a chick and nest count in the initial season
  abundance %>%
    dplyr::filter(initial_season == season_relative) %>%
    group_by(site_id, season, site, season_relative) %>%
    arrange(desc(type)) %>%
    slice(2) %>%
    ungroup() %>%
    dplyr::select(site_id, site, ccamlr, region, season, season_relative, count, sigma, precision))

# moment match alpha shape and rate parameters for breeding productivity
mu <- .5
sigma <- .25
a <- (mu^2 - mu^3 - mu * sigma^3) / sigma^2
b <- (mu - 2* mu^2 + mu^3 - sigma^2 + mu * sigma^3) / sigma^2

## create triregion vector
triregion <- rep(0, length(as.vector(SiteList$region)))
triregion[as.vector(SiteList$region) == 1 | as.vector(SiteList$region) == 2 | as.vector(SiteList$region) == 3 | as.vector(SiteList$region) == 4 | as.vector(SiteList$region) == 6] <- 1 # AP
triregion[as.vector(SiteList$region) == 5] <- 2 # Ross Sea
triregion[as.vector(SiteList$region) == 7 | as.vector(SiteList$region) == 8] <- 3 # Eastern Antarctica
n_triregions <- 3

## add ACBR data to SiteList
acbr_df <- read.csv(file = 'all_MAPPPD_acbr.csv')
SiteList$ACBR_ID <- acbr_df$ACBR_ID[match(SiteList$site_id, acbr_df$site_id)]
SiteList$ACBR_Name <- acbr_df$ACBR_Name[match(SiteList$site_id, acbr_df$site_id)]
SiteList$ACBR_ID <- acbr_df$ACBR_ID[match(SiteList$site_id, acbr_df$site_id)]
SiteList$ACBR_ID[SiteList$site_id == "HUKU"] <- 2
SiteList$ACBR_Name[SiteList$site_id == "HUKU"] <- "South Orkney Islands"
SiteList$ACBR_ID[SiteList$site_id == "PCOR"] <- 5
SiteList$ACBR_Name[SiteList$site_id == "PCOR"] <- "Enderby Land"
acbr_regions <- as.vector(SiteList$ACBR_ID)
n_acbr_regions <- 16 ## really 14: 1-5, 7-10, 12-16


# add ACBR data to abundance df
abundance$ACBR_ID <- SiteList$ACBR_ID[match(abundance$site_id, SiteList$site_id)]
abundance$ACBR_Name <- SiteList$ACBR_Name[match(abundance$site_id, SiteList$site_id)]
# sum(abundance$ACBR_ID == 1) # number of abundance observations for ACBR 1

# create the data list for the JAGS model
model_data <- list(
  nests = nrow(abundance_nests),
  y_n = log(abundance_nests$count), 
  precision_n = abundance_nests$precision,
  site_n = abundance_nests$site,
  season_n = abundance_nests$season_relative,
  chicks = nrow(abundance_chicks),
  y_c = log(abundance_chicks$count), 
  precision_c = abundance_chicks$precision,
  site_c = abundance_chicks$site,
  season_c = abundance_chicks$season_relative,
  y_i = log(abundance_initial$count),
  precision_i = abundance_initial$precision,
  n_sites = n_sites,
  n_seasons = n_seasons,
  n_regions = n_regions,
  n_ccamlr = n_ccamlr,
  n_triregions = n_triregions,
  n_acbr_regions = n_acbr_regions,
  s = as.vector(SiteList$initial_season),
  region = as.vector(SiteList$region),
  triregion = triregion,
  acbr_regions = acbr_regions,
  ccamlr = as.vector(SiteList$ccamlr),
  w = w,
  a = a,
  b = b)
```

```{r, echo = FALSE, eval = TRUE}
# create frame showing for each site x season whether nest, chicks, both, or nothing was observed
abundance_viz <- abundance %>%
  dplyr::select(site_id, season, type, count) %>%
  pivot_wider(names_from = type, values_from = count) %>%
  mutate(type = case_when(
    !is.na(nests) & is.na(chicks) ~ 1,
    is.na(nests) & !is.na(chicks) ~ 2, 
    !is.na(nests) & !is.na(chicks) ~ 3)) %>%
  dplyr::select(site_id, season, type)

save(model_data, file = "_static/model_data.rda")
save(SiteList, file = "_static/SiteList.rda")
save(abundance_chicks, file = "_static/abundance_chicks.rda")
save(abundance_nests, file = "_static/abundance_nests.rda")
save(abundance_initial, file = "_static/abundance_initial.rda")
save(w_df, file = "_static/w_df.rda")
save(w_template, file = "_static/w_template.rda")
```

## Site breeding visualized

```{r, eval = TRUE, echo = FALSE, fig.align = "center", fig.height = 40, fig.width = 12, warning = FALSE, fig.cap = "Seasonal presence/absence breeding data for each site. Blue (gray) filled boxes indicate the presence (absence) of breeding where border color indicates whether breeding status was observed (black) or imputed (no border)."}
ggplot(w_df, aes(x = factor(season), y = factor(site_id_rev), fill = as.factor(w))) +
  geom_tile(aes(color = as.factor(known_w), width = .8, height = .8), size = .75)  +
  scale_colour_manual(values = c("white", "black"), na.value = NA) +
  scale_fill_manual(values = alpha(c("gray", "blue"), .5), na.value = NA) +
  labs(x = "", y = "") +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_discrete(expand = c(0, 0), breaks = seq(1970, 2015, 5), 
    labels = c("1970", "1975", "1980", "1985", "1990", "1995", "2000", "2005", "2010", "2015"))  +
  theme_grey(base_size = 8) +      
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 8),
    axis.ticks = element_line(size = .6),
    plot.background = element_blank(),
    panel.background = element_blank(),
    panel.border=element_blank(),
    legend.position = "none")  
```
