# Model Fit

## Model fitting

```{r}
random_inits <- function(model_data) {
  seed = runif(1, 1, 100000)
  gamma <- runif(16, -.025, .025) # for each region
  # gamma[6] <- NA
  # gamma[10] <- NA
  # gamma[11] <- NA
  nu <- runif(16, 0.05, 40) ###   # ACBR #############
  # nu[6] <- NA
  # nu[10] <- NA
  # nu[11] <- NA
  #nu <- rtruncnorm(3, 0, 40, mean = 0, sd = 45)
  # sigma_region <- runif(1, .05, .1)
  # sigma_site <- runif(1, .025, .05)
  # sigma_season <- runif(1, .05, .1)
  sigma <- runif(16, .05, .1) ####################
  chicks <- model_data$chicks
  n_sites <- model_data$n_sites
  n_seasons <- model_data$n_seasons
  n_regions <- model_data$n_regions
  n_triregions <- model_data$n_triregions
  n_acbr_regions <- model_data$n_acbr_regions
  s <- model_data$s
  region <- model_data$region
  triregion <- model_data$triregion
  acbr_regions <- model_data$acbr_regions
  ccamlr <- model_data$ccamlr
  y_c <- model_data$y_c
  y_i <- model_data$y_i
  site_c <- model_data$site_c
  season_c <- model_data$season_c
  a <- model_data$a
  b <- model_data$b
  # eta <- rnorm(n_sites, 0, sigma_site)
  alpha <- rbeta(chicks, a, b)
  zr <- NA
  lz <- array(NA, dim = c(n_sites, n_seasons))
  #
  for (i in 1:n_sites) {
    lz[i, s[i]] <- mean(y_i[i], na.rm = TRUE)
    for (t in (s[i] + 1):n_seasons) {
      zr[i] <- gamma[acbr_regions[i]] # + eta[i]
      lz[i, t] <- LaplacesDemon::rst(1, lz[i, (t - 1)] + zr[i], sigma[acbr_regions[i]], nu[acbr_regions[i]])
    }
    for (t in 1:(s[i] - 1)) {
      zr[i] <- gamma[acbr_regions[i]] # + eta[i]
      lz[i, (s[i] - t)] <- LaplacesDemon::rst(1, lz[i, (s[i] - t + 1)] - zr[i], sigma[acbr_regions[i]], nu[acbr_regions[i]])
     }
  }

  z_c <- N <- NA
  for (i in 1:chicks) {
    if (lz[site_c[i], season_c[i]] < 0) lz[site_c[i], season_c[i]] <- 0
    N[i] <- 2 * round(exp(lz[site_c[i], season_c[i]]))
    z_c[i] <- base::max(rbinom(1, prob = alpha[i], N[i]), 1)
  }
  
  return(list(
    sigma = sigma, #######
    # sigma_site = sigma_site,
    gamma = gamma,
    # eta = eta,
    alpha = alpha,
    nu = nu, ###
    lz = lz,
    z_c = z_c,
    .RNG.name = "base::Mersenne-Twister",
    .RNG.seed = seed))
}

save(random_inits, file = "_static/random_inits.rda")
expect_error(random_inits(model_data), NA)
```

```{r, eval = FALSE, echo = TRUE}
n.chains <- 3
n.adapt <- 10000
n.update <- 25000
n.iter <- 25000
thin <- 10
cl <- makeCluster(n.chains)
cvars <- c("model_data", "n.adapt", "n.update", "n.iter", "thin", "params", "random_inits")
params <- c("gamma",  "sigma", "alpha", "z_c", "lz", "gl_a", "l_a", "y_i_new",
            "y_n_new", "y_c_new", "y_n_sqs", "y_n_sqs_new", "y_i_sqs_new", "y_i_sqs",
            "y_c_sqs", "y_c_sqs_new", "lz_c", "lza", "nu", "mu_lz")
parallel::clusterExport(cl, cvars)
out <- clusterEvalQ(cl, {
  library(rjags)
  inits <- random_inits(model_data)
  jm = jags.model("_static/jags_model.jags", data = model_data, n.chains = 1, n.adapt = n.adapt, 
    inits = inits)
  update(jm, n.iter = n.update)
  zm = coda.samples(jm, variable.names = params, n.iter = n.iter, thin = thin)
  return(as.mcmc(zm))
})
stopCluster(cl)
model_data_rinits_output = mcmc.list(out)  
save(model_data_rinits_output, file = "_static/model_data_rinits_output.rda")
```

```{r, fig.align = "center", fig.width = 12, fig.height = 8, fig.cap = "Trace plots for average intrinsic rate of growth and model variances (reported as standard devations)"}
MCMCsummary(model_data_rinits_output, params = c("gamma", "sigma", "nu"), HPD = TRUE, hpd_prob = .95, round = 3)
color_scheme_set("viridis")
bayesplot_theme_update(text = element_text(size = 14, family = "sans"))
mcmc_trace(model_data_rinits_output, regex_pars = c("sigma", "nu"))
```

```{r, fig.align='center', echo = FALSE}
sigmas <- MCMCsummary(model_data_rinits_output, params = c("sigma"), HPD = TRUE, hpd_prob = .95, round = 3)[,1]
nus <- MCMCsummary(model_data_rinits_output, params = c("nu"), HPD = TRUE, hpd_prob = .95, round = 3)[,1]
df16 <- data.frame("Region" = 1:16, "sigma" = sigmas, "nu" = nus)
library(ggplot2)
ggplot(df16, aes(x=sigma, y=nu)) +
  geom_point(
    color = "blue",
    fill = "#69b3a2",
    shape = 21,
    alpha = 0.6,
    size = 3,
    stroke = 1
    )
```


```{r, fig.align = "center", echo = FALSE}
prior <- rtruncnorm(15000, a=0.5, b=Inf, mean = 0, sd = 45)
MCMCtrace(model_data_rinits_output, params = c("nu[1]", "nu[2]", "nu[5]", "nu[6]", "nu[9]", "nu[10]", "nu[3]", "nu[4]", "nu[7]", "nu[8]", "nu[11]", "nu[12]", "nu[13]", "nu[14]", "nu[15]", "nu[16]"), priors = prior, pdf = FALSE, ISB = FALSE, exact = TRUE, type = "density")

```



```{r, fig.align = "center", echo = FALSE}
prior <- rtruncnorm(15000, a=0.5, b=Inf, mean = 0, sd = 45)
MCMCtrace(model_data_rinits_output, params = c("nu[6]", "nu[10]", "nu[11]", "nu[15]", "nu[4]", "nu[1]", "nu[12]", "nu[14]", "nu[9]", "nu[13]", "nu[2]", "nu[16]", "nu[5]", "nu[8]", "nu[7]", "nu[3]"), priors = prior, pdf = FALSE, ISB = FALSE, exact = TRUE, type = "density")

```



```{r, fig.align = "center", echo = FALSE}
prior <- rtruncnorm(15000, a=0.5, b=Inf, mean = 0, sd = 45)
MCMCtrace(model_data_rinits_output, params = c("sigma[1]", "sigma[2]", "sigma[5]", "sigma[6]", "sigma[9]", "sigma[10]", "sigma[3]", "sigma[4]", "sigma[7]", "sigma[8]", "sigma[11]", "sigma[12]", "sigma[13]", "sigma[14]", "sigma[15]", "sigma[16]"), priors = prior, pdf = FALSE, ISB = FALSE, exact = TRUE, type = "density")

```



```{r, fig.align = "center", echo = FALSE}
prior <- rtruncnorm(15000, a=0.5, b=Inf, mean = 0, sd = 45)
MCMCtrace(model_data_rinits_output, params = c("sigma[6]", "sigma[10]", "sigma[11]", "sigma[15]", "sigma[4]", "sigma[1]", "sigma[12]", "sigma[14]", "sigma[9]", "sigma[13]", "sigma[2]", "sigma[16]", "sigma[5]", "sigma[8]", "sigma[7]", "sigma[3]"), priors = prior, pdf = FALSE, ISB = FALSE, exact = TRUE, type = "density")

```

## Posterior predictive checks

```{r}
params <- c("y_i_sqs", "y_i_sqs_new", "y_n_sqs", "y_n_sqs_new", "y_c_sqs", "y_c_sqs_new")
MCMCsummary(model_data_rinits_output, params = params, n.eff = FALSE, round = 3)
```

```{r, fig.align = 'center', fig.width = 12, echo = FALSE}
rep_data <- MCMCvis::MCMCchains(model_data_rinits_output, params = 'y_i_new')
tdata_i <- bayesplot::ppc_data(model_data$y_i, rep_data)
rep_data <- MCMCvis::MCMCchains(model_data_rinits_output, params = 'y_n_new')
tdata_n <- bayesplot::ppc_data(model_data$y_n, rep_data)
rep_data <- MCMCvis::MCMCchains(model_data_rinits_output, params = 'y_c_new')
tdata_c <- bayesplot::ppc_data(model_data$y_c, rep_data)

ppc1 <- ggplot(tdata_i, aes_(x = ~value)) +
  stat_density(aes_(group = ~rep_id, color = "simulated data"), geom = "line", position = "identity", 
    size = 0.25, alpha = 0.1, trim = FALSE, bw = 'nrd0', adjust = 1, kernel = 'gaussian', n = 1024,
    data = function(x) dplyr::filter(x, !tdata_i$is_y)) +  
  stat_density(aes_(color = "y"), data = function(x) dplyr::filter(x, tdata_i$is_y), geom = "line", 
    position = "identity", lineend = "round", size = 0.5, trim = FALSE, bw = 'nrd0', adjust = 1, 
    kernel = 'gaussian', n = 1024) +
  scale_color_manual(values = c('firebrick3', 'black')) +
  theme_classic() +
  labs(title = "Initial Abundance Density Plot", x = "logged nest abundance") +
  theme(legend.position = "bottom")  

ppc2 <- ggplot(tdata_n, aes_(x = ~value)) +
  stat_density(aes_(group = ~rep_id, color = "simulated data"), geom = "line", position = "identity", 
    size = 0.25, alpha = 0.1, trim = FALSE, bw = 'nrd0', adjust = 1, kernel = 'gaussian', n = 1024,
    data = function(x) dplyr::filter(x, !tdata_n$is_y)) +  
  stat_density(aes_(color = "y"), data = function(x) dplyr::filter(x, tdata_n$is_y), geom = "line", 
    position = "identity", lineend = "round", size = 0.5, trim = FALSE, bw = 'nrd0', adjust = 1, 
    kernel = 'gaussian', n = 1024) +
  scale_color_manual(values = c('firebrick3', 'black')) +
  theme_classic() +
  labs(title = "Nest Abundance Density Plot", x = "logged nest abundance") +
  theme(legend.position = "bottom")  

ppc3 <- ggplot(tdata_c, aes_(x = ~value)) +
  stat_density(aes_(group = ~rep_id, color = "simulated data"), geom = "line", position = "identity", 
    size = 0.25, alpha = 0.1, trim = FALSE, bw = 'nrd0', adjust = 1, kernel = 'gaussian', n = 1024,
    data = function(x) dplyr::filter(x, !tdata_c$is_y)) +  
  stat_density(aes_(color = "y"), data = function(x) dplyr::filter(x, tdata_c$is_y), geom = "line", 
    position = "identity", lineend = "round", size = 0.5, trim = FALSE, bw = 'nrd0', adjust = 1, 
    kernel = 'gaussian', n = 1024) +
  scale_color_manual(values = c('firebrick3', 'black')) +
  theme_classic() +
  labs(title = "Chick Abundance Density Plot", x = "logged chick abundance") +
  theme(legend.position = "bottom")  

ppc1 + ppc2 + ppc3
```

## Posterior predictive loss

```{r}
y_i_new_mean <- MCMCsummary(model_data_rinits_output, params = c("y_i_new"), n.eff = FALSE)[, 1]
y_i_new_sd <- MCMCsummary(model_data_rinits_output, params = c("y_i_new"), n.eff = FALSE)[, 2]
dsel_i <- sum((model_data$y_i - y_i_new_mean)^2) + sum(y_i_new_sd^2)
y_n_new_mean <- MCMCsummary(model_data_rinits_output, params = c("y_n_new"), n.eff = FALSE)[, 1]
y_n_new_sd <- MCMCsummary(model_data_rinits_output, params = c("y_n_new"), n.eff = FALSE)[, 2]
(dsel_n <- sum((model_data$y_n - y_n_new_mean)^2) + sum(y_n_new_sd^2) + dsel_i)
y_c_new_mean <- MCMCsummary(model_data_rinits_output, params = c("y_c_new"), n.eff = FALSE)[, 1]
y_c_new_sd <- MCMCsummary(model_data_rinits_output, params = c("y_c_new"), n.eff = FALSE)[, 2]
(dsel_c <- sum((model_data$y_c- y_c_new_mean)^2) + sum(y_c_new_sd^2))
save(dsel_i, dsel_n, dsel_c, file = "_static/ppl.rda")
```

```{r, echo = FALSE, fig.align = "center", fig.height = 40, fig.width = 12, warning = FALSE, fig.cap = "Scaled nest posterior predictive loss by site and season."}
abundance_nests$dsel_n_sim <- (model_data$y_n - y_n_new_mean)^2 + y_n_new_sd^2
abundance_initial$dsel_n_sim <- (model_data$y_i - y_i_new_mean)^2 + y_i_new_sd^2
work1 <- rbind(
  abundance_nests %>% 
    dplyr::select(site, season_relative, dsel_n_sim),
  abundance_initial %>% 
    dplyr::select(site, season_relative, dsel_n_sim)) %>%
  mutate(dsel_n_sim_scaled = dsel_n_sim / base::max(dsel_n_sim)) %>%
  right_join(w_template, by = c("site", "season_relative")) %>%
  mutate(site_id_rev = factor(site_id, levels = rev(sort(unique(site_id))))) %>%
  dplyr::select(site_id, site_id_rev, season, dsel_n_sim_scaled) %>%
  arrange(site_id, season)
  
p1 <- ggplot(work1, aes(x = factor(season), y = factor(site_id_rev), fill = dsel_n_sim_scaled)) +
  geom_tile(color = "black", width = .8, height = .8, size = .3) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "white", name = "Scaled PPL") +
  labs(x = "", y = "") +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_discrete(expand = c(0, 0), breaks = seq(1970, 2015, 5), 
    labels = c("1970", "1975", "1980", "1985", "1990", "1995", "2000", "2005", "2010", "2015"))  +
  theme_grey(base_size = 8) +      
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 8),
    axis.ticks = element_line(size = .6),
    plot.background = element_blank(),
    panel.background = element_blank(),
    panel.border=element_blank(),
    legend.position = "bottom",
    legend.key.width = unit(2, "cm"))
p1
```

```{r, echo = FALSE, fig.align = "center", fig.height = 40, fig.width = 12, warning = FALSE, fig.cap = "Scaled chick posterior predictive loss by site and season."}
abundance_chicks$dsel_c_sim <- (model_data$y_c - y_c_new_mean)^2 + y_c_new_sd^2
work2 <- abundance_chicks %>%
  dplyr::select(site, season_relative, dsel_c_sim) %>%
  mutate(dsel_c_sim_scaled = dsel_c_sim / base::max(dsel_c_sim)) %>%
  right_join(w_template, by = c("site", "season_relative")) %>%
  mutate(site_id_rev = factor(site_id, levels = rev(sort(unique(site_id))))) %>%
  dplyr::select(site_id, site_id_rev, season, dsel_c_sim_scaled) %>%
  arrange(site_id, season)
  
p2 <- ggplot(work2, aes(x = factor(season), y = factor(site_id_rev), fill = dsel_c_sim_scaled)) +
  geom_tile(color = "black", width = .8, height = .8, size = .3) +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "white", name = "Scaled PPL") +
  labs(x = "", y = "") +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_discrete(expand = c(0, 0), breaks = seq(1970, 2015, 5), 
    labels = c("1970", "1975", "1980", "1985", "1990", "1995", "2000", "2005", "2010", "2015"))  +
  theme_grey(base_size = 8) +      
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 8),
    axis.ticks = element_line(size = .6),
    plot.background = element_blank(),
    panel.background = element_blank(),
    panel.border=element_blank(),
    legend.position = "bottom",
    legend.key.width = unit(2, "cm"))
p2
```


```{r, echo = FALSE, fig.align="center", fig.cap="Histogram of nest posterior predictive loss values for site/year combinations with counts"}
df_dsel <- data.frame(abundance_nests$dsel_n_sim)

ggplot(df_dsel, aes(x=abundance_nests.dsel_n_sim)) +
  geom_histogram(binwidth=0.05, color="black", fill="#EBB261") +
  labs(title="Nest PPL histogram", x="nest posterior predictive loss")
```


## Parameter visualization

```{r, echo = FALSE}
r_threshold <- 1.05
z_c_q <- MCMCsummary(model_data_rinits_output, params = c("z_c"), HPD = TRUE, hpd_prob = .95, round = 3)[,c(3, 4, 5, 6)]
z_c <- cbind(data.frame(z_c_q), abundance_chicks) %>%
  mutate(no_converged = ifelse(Rhat <= r_threshold | is.na(Rhat), 0, 1)) %>%
  dplyr::select(site_id, site_id, season, no_converged) %>%
  summarise(no_converged = sum(no_converged))

alpha_q <- MCMCsummary(model_data_rinits_output, params = c("alpha"), HPD = TRUE, hpd_prob = .95, round = 3)[,c(3, 4, 5, 6)]
alpha <- cbind(data.frame(alpha_q), abundance_chicks) %>%
  mutate(no_converged = ifelse(Rhat <= r_threshold | is.na(Rhat), 0, 1)) %>%
  dplyr::select(site_id, site_id, season, no_converged) %>%
  summarise(no_converged = sum(no_converged))
```

Of the `r dim(z_c_q)[1]` latent chick abundances and breeding productivity parameters, `r z_c$no_converged` abundance and `r alpha$no_converged` breeding productivity parameters failed to converge. We visualize additional parameters below. 

```{r, fig.align = "center", fig.height = 40, fig.width = 12, echo = FALSE, warning = FALSE, fig.cap = "Convergence and uncertainty of latent nest abundance estimates across all sites and seasons. Border color indicates the type of count observed for that site and season with purple being nest only, orange being chick only, and red being both nest and chick. Black dots mark abundance estimates that failed to converge."}

lz_q <- data.frame(MCMCsummary(model_data_rinits_output, params = c("lz"), HPD = FALSE, hpd_prob = .95, 
  round = 3, n.eff = TRUE))[, c(1, 2, 6, 7)]
work3 <- cbind(lz_q, w_template) %>%
  mutate(season = season_relative + min_season - 1) %>%
  arrange(site, season_relative) %>%
  mutate(converged = ifelse(Rhat <= r_threshold, NA, 4)) %>%
  mutate(neff_adequate = ifelse(n.eff > 500, NA, 4)) %>%
  left_join(abundance_viz, by = c("site_id", "season")) %>%
  mutate(sd_w = sd * mean) %>%
  mutate(site_id_rev = factor(site_id, levels = rev(sort(unique(site_id))))) %>%
  dplyr::select(site_id, site_id_rev, season, sd_w, Rhat, converged, n.eff, neff_adequate, type)

p3 <- ggplot(work3, aes(x = factor(season), y = factor(site_id_rev), fill = sd_w)) +
  geom_tile(aes(color = as.factor(type), width = .8, height = .8), size = .75)  +
  scale_fill_gradient2(low = "white", high = "green", name = "Mean-weighted logged abundance SD") +
  scale_colour_manual(values = c("purple", "orange", "red", "black"), na.value = NA, guide = FALSE) +
  geom_point(aes(color = as.factor(converged)), size = 1) +
  labs(x = "", y = "") +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_discrete(expand = c(0, 0), breaks = seq(1970, 2015, 5), 
    labels = c("1970", "1975", "1980", "1985", "1990", "1995", "2000", "2005", "2010", "2015")) +
  theme_grey(base_size = 8) +      
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 8),
    axis.ticks = element_line(size = .6),
    plot.background = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(), 
    legend.position = "bottom",
    legend.key.width = unit(2, "cm"))
p3
```

<br>

```{r, fig.align = "center", fig.height = 40, fig.width = 12, echo = FALSE, warning = FALSE, fig.cap = "Effective sample size of latent nest abundance estimates across all sites and seasons. Border color indicates the type of count observed for that site and season with purple being nest only, orange being chick only, and red being both nest and chick. Black dots mark abundance estimates that have fewer than 500 effective samples."}

p4 <- ggplot(work3, aes(x = factor(season), y = factor(site_id_rev), fill = n.eff)) +
  geom_tile(aes(color = as.factor(type), width = .8, height = .8), size = .75)  +
  scale_fill_gradient2(low = "white", high = "green", name = "Effective sample size") +
  scale_colour_manual(values = c("purple", "orange", "red", "black"), na.value = NA, guide = FALSE) +
  geom_point(aes(color = as.factor(neff_adequate)), size = 1) +
  labs(x = "", y = "") +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_discrete(expand = c(0, 0), breaks = seq(1970, 2015, 5), 
    labels = c("1970", "1975", "1980", "1985", "1990", "1995", "2000", "2005", "2010", "2015")) +
  theme_grey(base_size = 8) +      
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 8),
    axis.ticks = element_line(size = .6),
    plot.background = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(), 
    legend.position = "bottom",
    legend.key.width = unit(2, "cm"))
p4
```

<br>

<!-- ```{r, fig.align = "center", fig.height = 40, fig.width = 12, echo = FALSE, eval = TRUE, warning = FALSE, fig.cap = " Convergence and uncertainty of latent population growth rate multipliers across all sites and seasons. Green (yellow) filled boxes indicate that the population growth multiplier 95% highest posterior density credible was above (below) 1, while gray boxes indicate the generating value was within the HPDC interval. Border color indicates the type of count observed for that site and season with purple being nest only, orange being chick only, and red being both nest and chick. Black dots mark population growth rate multipliers that failed to converge."} -->

<!-- l_a_q <- data.frame(MCMCsummary(model_data_rinits_output, params = c("l_a"), HPD = FALSE, hpd_prob = .95,  -->
<!--   round = 3, n.eff = TRUE))[, c(2, 6, 7)] -->
<!-- work4 <- cbind(l_a_q, w_template %>%  -->
<!--   dplyr::filter(season_relative < n_seasons)) %>% -->
<!--   mutate(season = season_relative + min_season - 1) %>% -->
<!--   arrange(site, season_relative) %>% -->
<!--   mutate(converged = ifelse(Rhat <= r_threshold, NA, 4)) %>% -->
<!--   mutate(neff_adequate = ifelse(n.eff > 500, NA, 4)) %>% -->
<!--   left_join(abundance_viz, by = c("site_id", "season")) %>% -->
<!--   mutate(site_id_rev = factor(site_id, levels = rev(sort(unique(site_id))))) %>% -->
<!--   dplyr::select(site_id, site_id_rev, season, sd, Rhat, converged, n.eff, neff_adequate, type) -->

<!-- p5 <- ggplot(work4, aes(x = factor(season), y = factor(site_id_rev), fill = sd)) + -->
<!--   geom_tile(aes(color = as.factor(type), width = .8, height = .8), size = .75)  + -->
<!--   scale_fill_gradient2(low = "white", high = "green", name = "Lambda SD") + -->
<!--   scale_colour_manual(values = c("purple", "orange", "red", "black"), na.value = NA, guide = FALSE) + -->
<!--   geom_point(aes(color = as.factor(converged)), size = 1) + -->
<!--   labs(x = "", y = "") + -->
<!--   scale_y_discrete(expand = c(0, 0)) + -->
<!--   scale_x_discrete(expand = c(0, 0), breaks = seq(1970, 2015, 5),  -->
<!--     labels = c("1970", "1975", "1980", "1985", "1990", "1995", "2000", "2005", "2010", "2015")) + -->
<!--   theme_grey(base_size = 8) +       -->
<!--   theme( -->
<!--     axis.text.x = element_text(size = 10), -->
<!--     axis.text.y = element_text(size = 8), -->
<!--     axis.ticks = element_line(size = .6), -->
<!--     plot.background = element_blank(), -->
<!--     panel.background = element_blank(), -->
<!--     panel.border = element_blank(),  -->
<!--     legend.position = "bottom", -->
<!--     legend.key.width = unit(2.5, "cm")) -->
<!-- p5 -->
<!-- ``` -->

```{r, fig.align = "center", echo = FALSE, fig.cap = "Equal tailed credible intervals of the posterior distributions for model variances (reported as standard devations). Thin (thick) lines represent 95% (50%) credible intervals and points represent posterior medians."}
#MCMCplot(model_data_rinits_output, params = "sigma", horiz = TRUE, guide_lines = TRUE)
```


```{r, fig.align = "center", echo = FALSE, fig.cap = "Equal tailed credible intervals of the posterior distributions for degrees of freedom of student t distributions for each region (reported as standard devations). Thin (thick) lines represent 95% (50%) credible intervals and points represent posterior medians."}
MCMCplot(model_data_rinits_output, params = c("sigma[1]", "sigma[2]", "sigma[3]", "sigma[4]", "sigma[5]", "sigma[6]", "sigma[7]", "sigma[8]"), horiz = TRUE, guide_lines = TRUE, ISB = FALSE, exact = TRUE)

MCMCplot(model_data_rinits_output, params = c("sigma[9]", "sigma[10]", "sigma[11]", "sigma[12]", "sigma[13]", "sigma[14]", "sigma[15]", "sigma[16]"), horiz = TRUE, guide_lines = TRUE, ISB = FALSE, exact = TRUE)

```


```{r, fig.align = "center", echo = FALSE, fig.cap = "Equal tailed credible intervals of the posterior distributions for degrees of freedom of student t distributions for each region (reported as standard devations). Thin (thick) lines represent 95% (50%) credible intervals and points represent posterior medians."}
MCMCplot(model_data_rinits_output, params = c("nu[1]", "nu[2]", "nu[3]", "nu[4]", "nu[5]", "nu[6]", "nu[7]", "nu[8]"), horiz = TRUE, guide_lines = TRUE, ISB = FALSE, exact = TRUE)

MCMCplot(model_data_rinits_output, params = c("nu[9]", "nu[10]", "nu[11]", "nu[12]", "nu[13]", "nu[14]", "nu[15]", "nu[16]"), horiz = TRUE, guide_lines = TRUE, ISB = FALSE, exact = TRUE)

```

```{r, fig.align = "center", echo = FALSE, fig.cap = "Equal tailed credible intervals of the posterior distributions for degrees of freedom of student t distributions for each region (reported as standard devations). Thin (thick) lines represent 95% (50%) credible intervals and points represent posterior medians."}
#### by number of sites
MCMCplot(model_data_rinits_output, params = c("nu[6]", "nu[10]", "nu[11]", "nu[15]", "nu[4]", "nu[1]", "nu[12]", "nu[14]"), horiz = TRUE, guide_lines = TRUE, ISB = FALSE, exact = TRUE)

MCMCplot(model_data_rinits_output, params = c("nu[9]", "nu[13]", "nu[2]", "nu[16]", "nu[5]", "nu[8]", "nu[7]", "nu[3]"), horiz = TRUE, guide_lines = TRUE, ISB = FALSE, exact = TRUE)

```



```{r, fig.align = "center", fig.height = 40, echo = FALSE, fig.cap = "Equal tailed credible intervals of the posterior distributions for breeding productivity. Thin (thick) lines represent 95% (50%) credible intervals and points represent posterior medians."}
MCMCplot(model_data_rinits_output, params = "alpha", horiz = TRUE, sz_labels = .6, ref = .5, guide_lines = TRUE, 
  xlim = c(0, 1), labels = paste(abundance_chicks$site_id, abundance_chicks$season, sep = "-"))
```


<!-- ```{r, fig.align = "center", fig.height = 40, echo = FALSE, fig.cap = "Equal tailed credible intervals of the posterior distributions for site-level average population growth rate multipliers. Thin (thick) lines represent 95% (50%) credible intervals and points represent posterior medians."} -->
<!-- MCMCplot(model_data_rinits_output, params = "gl_a", horiz = TRUE, labels = SiteList$site_id, sz_labels = .6,  -->
<!--   guide_lines = TRUE, ref = 1, xlim = c(.6, 1.4)) -->
<!-- ``` -->
